#!/usr/bin/env python3
"""Generates the `-dark.svg` from the light SVG by promoting the @media block.

Why it exists: the SVGs here already switch colors on their own through
`prefers-color-scheme`, and that works in any browser. The README, however, uses
`<picture>` with two files — the path GitHub documents, and the one that doesn't
depend on its sanitizer preserving the `<style>` inside the SVG.

    python3 assets/make-dark-variant.py assets/logo.svg

Run it after editing an original; the variant is derived and is not edited by hand.
"""
import sys
from pathlib import Path

MARKER = "@media (prefers-color-scheme: dark) {"


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2

    source = Path(sys.argv[1])
    svg = source.read_text()

    if MARKER not in svg:
        print(f"{source}: has no @media block to promote")
        return 1

    start = svg.index(MARKER)
    style_end = svg.index("</style>")
    block = svg[start:style_end]
    rules = block[block.index("{") + 1:block.rindex("}")]

    destination = source.with_name(source.stem + "-dark.svg")
    destination.write_text(
        svg[:start]
        + "    /* GENERATED by assets/make-dark-variant.py — do not edit. */\n"
        + rules
        + svg[style_end:]
    )
    print(f"{destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
